name: Deploy Mule App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: |
        mvn clean install -B -e -V -s .github/settings.xml
        mvn package -DskipTests -s .github/settings.xml
        
        # Verificación crítica del JAR
        if [ ! -f "target/ejemplogithub-*-mule-application.jar" ]; then
          echo "::error::JAR file not found!"
          ls -la target/
          exit 1
        fi

    - name: Get CloudHub Token
      id: get_token
      run: |
        RESPONSE=$(curl -s -X POST https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "client_id=${{ secrets.ANYPOINT_CLIENT_ID }}" \
          -d "client_secret=${{ secrets.ANYPOINT_CLIENT_SECRET }}" \
          -d "grant_type=client_credentials")
        
        TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
        if [ -z "$TOKEN" ]; then
          echo "::error::Token generation failed"
          echo "$RESPONSE"
          exit 1
        fi
        
        echo "TOKEN=$TOKEN" >> $GITHUB_ENV
        echo "::add-mask::$TOKEN"

    - name: Deploy to CloudHub
      run: |
        JAR_FILE=$(ls target/*-mule-application.jar)
        echo "Deploying $JAR_FILE"
        
        curl -X POST https://anypoint.mulesoft.com/cloudhub/api/v2/applications \
          -H "Authorization: Bearer ${{ env.TOKEN }}" \
          -H "X-ANYPNT-ORG-ID: ${{ secrets.ANYPOINT_ORG_ID }}" \
          -F "file=@$JAR_FILE" \
          -F "domain=ejemplogithub-$GITHUB_RUN_ID" \
          -F "runtime=4.4.0" \
          -F "region=us-east-1" \
          -F "workers=1" \
          -F "workerSize=0.1" \
          -F "monitoringEnabled=false"
